spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: autenticacion
          uri: http://auth:8083
          predicates:
            - Path=/cv/autenticacion/**
        
        - id: persona-autenticacion
          uri: http://auth:8083
          predicates:
            - Path=/cv/persona-autenticacion/**

        - id: persona
          uri: http://persona:8082
          predicates:
            - Path=/cv/persona/**

        - id: experiencias
          uri: http://experiencias:8084
          predicates:
            - Path=/cv/experiencias/**

        - id: estudios
          uri: http://estudios:8085
          predicates:
            - Path=/cv/estudios/**

        - id: cursos
          uri: http://cursos:8086
          predicates:
            - Path=/cv/cursos/**

        - id: projects
          uri: http://projects:8087
          predicates:
            - Path=/cv/projects/**

        - id: skills
          uri: http://skills:8088
          predicates:
            - Path=/cv/skills/**

server:
  port: 8080

app:
  jwt:
    secret: ${JWT_SECRET:clave-secreta-de-desarrollo-cambiar-en-produccion-256bits}
