spring:
  application:
    name: cvproject
  datasource:
    url: jdbc:postgresql://localhost:5432/cvdbnico
    username: cvdbnicouser
    password: Gardian@2
    driver-class-name: org.postgresql.Driver
    schema: cvdbnicoschema
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: cvdbnicoschema
server:
  port: 8080
  servlet:
    context-path: /cv

app:
  title: CV Project Application